"""add_user_state_id_column

Revision ID: 089b49d0b1f0
Revises: c5ce3fa1f315
Create Date: 2026-06-28 21:23:11.413196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '089b49d0b1f0'
down_revision: Union[str, None] = 'c5ce3fa1f315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('state_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'users', 'regions', ['state_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'state_id')
    # ### end Alembic commands ###
