"""add_regions_and_scope_columns

Revision ID: 1fae126e424f
Revises: 4228ea96b3e7
Create Date: 2026-06-28 12:31:59.264701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1fae126e424f'
down_revision: Union[str, None] = '4228ea96b3e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('parent_region_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("type IN ('state', 'district')", name='ck_region_type'),
    sa.ForeignKeyConstraint(['parent_region_id'], ['regions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_name'), 'regions', ['name'], unique=False)
    op.add_column('departments', sa.Column('region_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'departments', 'regions', ['region_id'], ['id'], ondelete='SET NULL')
    op.alter_column('issue_followers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.add_column('issues', sa.Column('region_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_issues_region_id'), 'issues', ['region_id'], unique=False)
    op.create_foreign_key(None, 'issues', 'regions', ['region_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('admin_scope', sa.String(), nullable=True))
    op.add_column('users', sa.Column('region_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'users', 'regions', ['region_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'region_id')
    op.drop_column('users', 'admin_scope')
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_index(op.f('ix_issues_region_id'), table_name='issues')
    op.drop_column('issues', 'region_id')
    op.alter_column('issue_followers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text("timezone('utc'::text, now())"))
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_column('departments', 'region_id')
    op.drop_index(op.f('ix_regions_name'), table_name='regions')
    op.drop_table('regions')
    # ### end Alembic commands ###
