"""add_region_geometry_columns

Revision ID: c5ce3fa1f315
Revises: 910205ff9cda
Create Date: 2026-06-28 21:01:02.059636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5ce3fa1f315'
down_revision: Union[str, None] = '910205ff9cda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regions', sa.Column('bbox_south', sa.Float(), nullable=True))
    op.add_column('regions', sa.Column('bbox_north', sa.Float(), nullable=True))
    op.add_column('regions', sa.Column('bbox_west', sa.Float(), nullable=True))
    op.add_column('regions', sa.Column('bbox_east', sa.Float(), nullable=True))
    op.add_column('regions', sa.Column('boundary_geojson', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regions', 'boundary_geojson')
    op.drop_column('regions', 'bbox_east')
    op.drop_column('regions', 'bbox_west')
    op.drop_column('regions', 'bbox_north')
    op.drop_column('regions', 'bbox_south')
    # ### end Alembic commands ###
