"""add_resolution_image_and_sla

Revision ID: fe1c49f3961b
Revises: 8486516615a7
Create Date: 2026-07-01 00:01:45.821528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe1c49f3961b'
down_revision: Union[str, None] = '8486516615a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('resolution_image_url', sa.String(), nullable=True))
    op.add_column('issues', sa.Column('sla_due_at', sa.DateTime(), nullable=True))
    op.drop_index('idx_issues_region', table_name='issues')
    op.drop_index('idx_regions_parent', table_name='regions')
    op.drop_index('idx_users_region', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'sla_due_at')
    op.drop_column('issues', 'resolution_image_url')
    op.create_index('idx_users_region', 'users', ['region_id'], unique=False)
    op.create_index('idx_regions_parent', 'regions', ['parent_region_id'], unique=False)
    op.create_index('idx_issues_region', 'issues', ['region_id'], unique=False)
    # ### end Alembic commands ###
